steps:
  - id: 'run unit test'
    name: 'gcr.io/cloud-builders/go'
    args: ['test', './...']
    env: ['PROJECT_ROOT=github.com/Kajekk/comtam']

  - id: 'build image'
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/comtam-deployment:$SHORT_SHA', '.']

  - id: 'push image'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/comtam-deployment:$SHORT_SHA'