apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: comtam-deployment
  name: comtam-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: comtam-deployment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: comtam-deployment
    spec:
      containers:
        - name: comtam-deployment
          image: gcr.io/$PROJECT_ID/comtam-deployment:latest
          ports:
            - containerPort: 8000
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: comtam-deployment
  name: comtam-deployment-hpa-fgvl
  namespace: default
spec:
  maxReplicas: 5
  metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 80
      type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: comtam-deployment
---
apiVersion: v1
kind: Service
metadata:
  name: comtam-deployment
spec:
  selector:
    app: comtam-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
